### PR TITLE
Remove early anonymous bitfield filtering and consolidate name method

### LINKED ISSUE #1007: Incorrect layout with large bitfield
Follow up to https://github.com/rust-lang-nursery/rust-bindgen/pull/1001

### Input C/C++ Header

```C++
struct {
  unsigned : 632;
} a;
```

### Bindgen Invocation

```
$ bindgen input.h
```

### Actual Results

Panic when running the layout tests: our generated struct ends up with the wrong size.

### Expected Results

We generate a struct with the correct layout, and it passes its layout tests.

### PR DESCRIPTION
**Pull request by aeleos**
This PR is some changes to early bitfield filtering to help fix (#1007) This does not close (#1007), but allows for checking if the bitfield is too large during a later stage.

@fitzgen r?

### CODE REVIEW

File: tests/expectations/tests/derive-hash-template-inst-float.rs [hunk 1]
```diff
@@ -102,31 +102,13 @@ fn __bindgen_test_layout_foo_open0_int_close0_instantiation() {
...
-    assert_eq!(
-        ::std::mem::align_of::<foo<f32>>(),
-        4usize,
-        concat!(
-            "Alignment of template specialization: ",
-            stringify!(foo<f32>)
-        )
-    );
+    assert_eq ! ( :: std :: mem :: size_of :: < foo < f32 > > ( ) , 4usize , concat ! ( "Size of template specialization: " , stringify ! ( foo < f32 > ) ) );
+    assert_eq ! ( :: std :: mem :: align_of :: < foo < f32 > > ( ) , 4usize , concat ! ( "Alignment of template specialization: " , stringify ! ( foo < f32 > ) ) );
```
Comment (fitzgen) [inline tests/expectations/tests/derive-hash-template-inst-float.rs]: I think if you update to the latest `rustfmt` then it should preserve the old formatting here.

```
$ rustup update nightly
$ cargo +nightly install rustfmt-nightly
```

**Comment by aeleos** [comment]
@fitzgen I think that fixed it, yea I did have an outdated version of rustfmt. I left it in because I thought that if it happened on the CI test it would fail, so I would need to keep it in, but I realize now that wouldn't have happened because it was just my rustfmt version.

**Comment by fitzgen** [comment]
@bors-servo r+

Thank you very much @aeleos !

**Comment by fitzgen** [comment]
I don't understand why our CI pushes get immediately cancelled all the time now... Restarted.
