### PR TITLE
Fix bitfields on big-endian machines.

### LINKED ISSUE #1340: Bitfields broken for big-endian machines.
See https://bugzilla.mozilla.org/show_bug.cgi?id=1462623

### PR DESCRIPTION
**Pull request by psumbera**
Fixes #1340

### CODE REVIEW

File: src/codegen/bitfield_unit.rs [hunk 1]
```diff
@@ -27,7 +27,12 @@ where
         let byte_index = index / 8;
         let byte = self.storage.as_ref()[byte_index];
 
-        let bit_index = index % 8;
+        let mut bit_index = index % 8;
+        #[cfg(target_endian = "big")]
```
Comment (upsuper) [inline src/codegen/bitfield_unit.rs]: It probably should use some runtime target information rather than build time config, because people may want to cross-compile.

Comment (emilio) [reply src/codegen/bitfield_unit.rs]: That's fine though, isn't it? This code is included in the target code.

Comment (upsuper) [reply src/codegen/bitfield_unit.rs]: Oh, this is the code bindgen adds to the generated binding file. That makes sense then.

**Comment by emilio** [comment]
Sorry for the lag here, this looks fine but the tests need to be updated. I'll get to it ASAP.
