### PR TITLE
codegen: Support repr(align)

### LINKED ISSUE #917: `alignas` alignment is not respected on Linux 32-bit
### Input C/C++ Header

```C++
template<class T>
class Maybe
{
  alignas(T) unsigned char mStorage[sizeof(T)];
  char mIsSome;
};

struct Keyframe
{
  Maybe<double> mOffset;
  int           mComputedOffset = 1.0;
};
```

### Bindgen Invocation

```
$ bindgen maybe.h -o maybe_bindings_32.rs --opaque-type Maybe -- -x c++ -std=c++14 -m32
```

### Actual Results

```rust
/* automatically generated by rust-bindgen */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Maybe {
}
#[repr(C)]
#[derive(Debug, Copy)]
pub struct Keyframe {
    pub mOffset: [u64; 2usize],
    pub mComputedOffset: ::std::os::raw::c_int,
}
#[test]
fn bindgen_test_layout_Keyframe() {
    assert_eq!(::std::mem::size_of::<Keyframe>() , 24usize , concat ! (
               "Size of: " , stringify ! ( Keyframe ) ));
    assert_eq! (::std::mem::align_of::<Keyframe>() , 8usize , concat ! (
                "Alignment of " , stringify ! ( Keyframe ) ));
    assert_eq! (unsafe {
                & ( * ( 0 as * const Keyframe ) ) . mOffset as * const _ as
                usize } , 0usize , concat ! (
                "Alignment of field: " , stringify ! ( Keyframe ) , "::" ,
                stringify ! ( mOffset ) ));
    assert_eq! (unsafe {
                & ( * ( 0 as * const Keyframe ) ) . mComputedOffset as * const
                _ as usize } , 16usize , concat ! (
                "Alignment of field: " , stringify ! ( Keyframe ) , "::" ,
                stringify ! ( mComputedOffset ) ));
}
impl Clone for Keyframe {
    fn clone(&self) -> Self { *self }
}
```

This layout test fails on Linux 32-bit:

```
$ rustc --test --target i686-unknown-linux-gnu maybe_bindings_32.rs
$ ./maybe_bindings_32

running 1 test
test bindgen_test_layout_Keyframe ... FAILED

failures:

---- bindgen_test_layout_Keyframe stdout ----
	thread 'bindgen_test_layout_Keyframe' panicked at 'assertion failed: `(left == right)` (left: `20`, right: `24`): Size of: Keyframe', maybe_bindings_32.rs:15
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    bindgen_test_layout_Keyframe

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

because Rust believes the alignment should be 4 bytes. `alignas` is trying to mandate 8 bytes, but Rust doesn't seem to agree.

### Expected Results

This is currently blocking Stylo from working on Linux 32-bit, see https://bugzilla.mozilla.org/show_bug.cgi?id=1366050#c49.

### PR DESCRIPTION
**Pull request by emilio**
Fixes #917.

### CODE REVIEW

File: tests/expectations/tests/repr-align.rs [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+
+#![allow(dead_code, non_snake_case, non_camel_case_types, non_upper_case_globals)]
+
+#[repr(C)]
+#[repr(align(8))]
+#[derive(Debug, Default, Copy, Clone)]
+pub struct a {
+    pub b: ::std::os::raw::c_int,
+    pub c: ::std::os::raw::c_int,
+    pub __bindgen_align: [u64; 0usize],
```
Comment (upsuper) [inline tests/expectations/tests/repr-align.rs]: Do we still need to generate this, then?

File: tests/headers/repr-align.hpp [hunk 2]
```diff
@@ -0,0 +1,6 @@
+// bindgen-flags: --rust-target 1.24 -- -std=c++11
+
+struct alignas(8) a {
```
Comment (upsuper) [inline tests/headers/repr-align.hpp]: Could you add another testcase with `alignas(double)`? And probably do so with 32bit Linux as target, given that's where the original issue is.

Also maybe add testcase for things when `alignas` is on field rather than type?

File: tests/expectations/tests/repr-align.rs (hunk 1 above)
Comment (emilio) [reply tests/expectations/tests/repr-align.rs]: Not really, but it doesn't hurt and avoids having the extra codepath and conditionals.

File: tests/headers/repr-align.hpp (hunk 2 above)
Comment (emilio) [reply tests/headers/repr-align.hpp]: Sure, will add. We don't run tests on linux32 though, so I won't do that, since it wouldn't test anything extra.

Comment (upsuper) [reply tests/headers/repr-align.hpp]: I think if you add `-m32` should be enough?

Comment (emilio) [reply tests/headers/repr-align.hpp]: Added

**Comment by upsuper** [comment]
@bors-servo r+

Although it would still be good if you have a test for `alignas` on member field. Also if we can remove the extra `__bindgen_align` field, but this can probably be done in a separate one.

**Comment by emilio** [comment]
So turns out this feature is really `1.25` in my testing :(
