### PR TITLE
Make bitfields larger than type opaque

### LINKED ISSUE #1007: Incorrect layout with large bitfield
Follow up to https://github.com/rust-lang-nursery/rust-bindgen/pull/1001

### Input C/C++ Header

```C++
struct {
  unsigned : 632;
} a;
```

### Bindgen Invocation

```
$ bindgen input.h
```

### Actual Results

Panic when running the layout tests: our generated struct ends up with the wrong size.

### Expected Results

We generate a struct with the correct layout, and it passes its layout tests.

### PR DESCRIPTION
**Pull request by aeleos**
@fitzgen r?

Fixes #1007 by ensuring that bitfields larger than type will be opaque, ensuring the layout is correct.

### CODE REVIEW

File: src/ir/comp.rs [hunk 1]
```diff
@@ -1473,8 +1473,27 @@ impl DotAttributes for CompInfo {
...
 
-    fn is_opaque(&self, _: &BindgenContext, _: &()) -> bool {
-        self.has_non_type_template_params
+    fn is_opaque(&self, ctx: &BindgenContext, _: &()) -> bool {
+        //Early return to avoid extra computation
+        if self.has_non_type_template_params {
+            return true
+        }
+
+        let has_large_bitfield = self.fields().iter().any(|f| match *f {
```
Comment (fitzgen) [inline src/ir/comp.rs]: Nitpick: rather than assigning the bool expression to a variable and then returning the variable, we should return the expression directly.

File: src/ir/comp.rs [hunk 2]
```diff
@@ -1473,8 +1473,27 @@ impl DotAttributes for CompInfo {
 impl IsOpaque for CompInfo {
     type Extra = ();
 
-    fn is_opaque(&self, _: &BindgenContext, _: &()) -> bool {
-        self.has_non_type_template_params
+    fn is_opaque(&self, ctx: &BindgenContext, _: &()) -> bool {
+        //Early return to avoid extra computation
```
Comment (fitzgen) [inline src/ir/comp.rs]: Nitpick: space between `//` and `Early`, and a period at the end of the sentence please :)
