### PR TITLE
Rewrite `has destructor` analysis as a fixed-point analysis

### LINKED ISSUE #927: Rewrite `has_destructor` as a fixed point analysis
Very similar to #765, you could look at the PR that fixed that issue and have a template for fixing this issue.

This will allow us to compute the information once and then cache the results, as well as remove the `detect_has_destructor_cycle` field.

I'm happy to mentor anyone who wants to pick this up.

### PR DESCRIPTION
**Pull request by bd339**
Fixes #927 . Note that this creates a dependency between the "cannot derive copy" and "has destructor" analysis, i.e. the "has destructor" analysis must run before the "cannot derive copy" analysis, because "cannot derive copy" needs the results of "has destructor".

### CODE REVIEW

File: src/ir/comp.rs [hunk 1]
```diff
@@ -989,6 +943,11 @@ impl CompInfo {
         return self.has_own_virtual_method;
     }
 
+    /// Does this type have a destructor?
+    pub fn has_destructor(&self) -> bool {
+        self.has_destructor
```
Comment (fitzgen) [inline src/ir/comp.rs]: Let's rename these to either `trivially_has_destructor` or `has_own_destructor` to clarify that this isn't looking through template instantiations or base members.

Comment (bd339) [reply src/ir/comp.rs]: Sure, good idea.

Comment (fitzgen) [reply src/ir/comp.rs]: Let me know when you update the PR, sometimes I don't get the new-commits-pushed emails for whatever reason. Thanks again!

Comment (bd339) [reply src/ir/comp.rs]: Have done so, but squashed and did a force push. Maybe that's why you didn't get an email?

**Comment by fitzgen** [comment]
@bors-servo r+

@bd339 thanks a bunch! Are you interested in hacking on bindgen some more? https://github.com/rust-lang-nursery/rust-bindgen/issues/933 could be a good issue to pick up, if you're interested :)
